#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jap-Nanak Makkar
email: jkm5ar@virginia.edu
description: 
  Doctoral candidate at the University of Virginia, Department of English.
  Researcher of digital technologies, critical theory and contemporary literature.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jmakr
github_username:  jmakr

# Build settings
markdown: kramdown
